import type { AgentSettledEvent, BeforeAgentStartEvent, BeforeProviderRequestEvent, ExtensionAPI, ExtensionContext, InputEvent, MessageEndEvent, SessionCompactEvent, SessionShutdownEvent, SessionStartEvent, ToolCallEvent, ToolExecutionEndEvent } from "@earendil-works/pi-coding-agent";
type Events = { session_start: SessionStartEvent; session_shutdown: SessionShutdownEvent; input: InputEvent; before_agent_start: BeforeAgentStartEvent; before_provider_request: BeforeProviderRequestEvent; tool_call: ToolCallEvent; tool_execution_end: ToolExecutionEndEvent; message_end: MessageEndEvent; session_compact: SessionCompactEvent; agent_settled: AgentSettledEvent };
type Handler<E extends keyof Events> = (event: Events[E], ctx: ExtensionContext) => unknown;
/** Synthetic Pi 0.82.1 lifecycle harness. */
export class ExtensionHarness {
  readonly commands = new Map<string, { handler: (args: string, ctx: ExtensionContext) => Promise<void> }>(); readonly status = new Map<string, string | undefined>(); readonly notifications: { message: string; type: string | undefined }[] = []; sessionId = "synthetic-session"; cwd = process.cwd(); model: unknown = { id: "synthetic", provider: "openai", api: "openai-responses", reasoning: true };
  private readonly handlers: { [E in keyof Events]: Handler<E>[] } = { session_start: [], session_shutdown: [], input: [], before_agent_start: [], before_provider_request: [], tool_call: [], tool_execution_end: [], message_end: [], session_compact: [], agent_settled: [] };
  get context() { return { cwd: this.cwd, model: this.model, sessionManager: { getSessionId: () => this.sessionId }, ui: { setStatus: (key: string, text: string | undefined) => this.status.set(key, text), notify: (message: string, type?: string) => this.notifications.push({ message, type }) } } as unknown as ExtensionContext; }
  on<E extends keyof Events>(event: E, handler: Handler<E>) { this.handlers[event].push(handler); } registerCommand(name: string, options: { handler: (args: string, ctx: ExtensionContext) => Promise<void> }) { this.commands.set(name, options); }
  emit<E extends keyof Events>(name: E, event: Events[E]): unknown { let out: unknown; for (const h of this.handlers[name]) { const x = h(event, this.context); if (x !== undefined) out = x; } return out; } api(): ExtensionAPI { return this as unknown as ExtensionAPI; }
  start(reason: SessionStartEvent["reason"] = "startup") { this.emit("session_start", { type: "session_start", reason } satisfies SessionStartEvent); } shutdown(reason: SessionShutdownEvent["reason"] = "new") { this.emit("session_shutdown", { type: "session_shutdown", reason } satisfies SessionShutdownEvent); } input(text: string) { this.emit("input", { type: "input", text, source: "interactive" } satisfies InputEvent); } before(prompt: string) { this.emit("before_agent_start", { type: "before_agent_start", prompt, systemPrompt: "", systemPromptOptions: {} } as BeforeAgentStartEvent); } request(payload: unknown) { return this.emit("before_provider_request", { type: "before_provider_request", payload } satisfies BeforeProviderRequestEvent); } error() { this.emit("tool_execution_end", { type: "tool_execution_end", toolCallId: "synthetic", toolName: "read", result: {}, isError: true } satisfies ToolExecutionEndEvent); } message(stopReason: "error" | "length" | "aborted" | "stop" | "toolUse", usage?: Record<string, number>) { this.emit("message_end", { type: "message_end", message: { role: "assistant", stopReason, ...(usage ? { usage } : {}) } } as unknown as MessageEndEvent); } settled() { this.emit("agent_settled", { type: "agent_settled" } satisfies AgentSettledEvent); }
}
