import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createExtension } from "../../src/index.js";
import { safeDefaults } from "../../src/config/defaults.js";
import type { EffortRouterConfig } from "../../src/config/schema.js";
import { ExtensionHarness } from "./extension-harness.js";
const dirs: string[] = []; const dir = () => { const p = mkdtempSync(join(tmpdir(), "pi-reap-pr4-")); dirs.push(p); return p; }; afterEach(() => dirs.splice(0).forEach((p) => rmSync(p, { recursive: true, force: true })));
const match = { provider: "openai", api: "openai-responses", model: "m", modelCatalogRevision: "catalog", modelCatalogDigest: "a".repeat(64), piVersion: "0.82.1", providerAdapterRevision: "adapter", providerAdapterDigest: "b".repeat(64) };
const capability = { schemaVersion: 1, profileId: "cap", profileRevision: "1", source: { kind: "repository-pinned", repositoryRevision: "synthetic" }, match, rungs: [{ id: "low", ordinal: 0, providerValue: "minimal", automaticEligible: true, explicitOnly: false }, { id: "high", ordinal: 1, providerValue: "high", automaticEligible: true, explicitOnly: false }], automaticFloor: "low", automaticCeiling: "high", anchors: { economical: "low", balanced: "high", deliberate: "high", exhaustive: "high" }, baselineBehavior: "preserve-request" } as const;
const selector = { kind: "automatic-ceiling" } as const; const admission = { schemaVersion: 1, profileId: "adm", profileRevision: "1", source: { kind: "repository-pinned", repositoryRevision: "synthetic" }, capabilityProfileId: "cap", capabilityProfileRevision: "1", initial: { simpleQuery: { kind: "lowest-automatic" }, boundedRead: selector, implementation: selector, debugging: selector, architecture: selector, highRisk: selector, continuation: selector, unknown: selector }, evidence: { firstToolError: { selector }, repeatedToolError: { selector }, providerError: { selector }, lengthExhaustion: { selector }, overflowRetry: { selector }, failedContinuation: { selector } } } as const;
const activation = { capability, admission, modelCatalogRevision: "catalog", modelCatalogDigest: "a".repeat(64), piVersion: "0.82.1", providerAdapterRevision: "adapter", providerAdapterDigest: "b".repeat(64) };
const config = (directory: string, mode: "shadow" | "enforce" = "shadow", enabled = true, includePromptText = false) => async (): Promise<EffortRouterConfig> => ({ enabled: true, mode, telemetry: { enabled, includePromptText, directory }, ui: { showStatus: true, notifyOnEscalation: false } });
async function run(h: ExtensionHarness, text = "synthetic secret"): Promise<unknown> { h.input(text); h.before(text); return h.request({ reasoning: { effort: "baseline" }, cache: "opaque" }); }
const records = (directory: string, file: string) => readFileSync(join(directory, file), "utf8").trim().split("\n").map((line) => JSON.parse(line) as Record<string, unknown>);
describe("profile-bound telemetry and shadow mode", () => {
  it("records bound profile data but excludes prompt and payload while shadow leaves payload untouched", async () => { const p = dir(); const h = new ExtensionHarness(); await createExtension({ load: config(p), activation })(h.api()); h.start(); expect(await run(h)).toBeUndefined(); h.message("stop", { input: 0, output: 2, reasoning: 3, cacheRead: 0, cacheWrite: 5, cost: { input: 0, output: 1, cacheRead: 0, cacheWrite: 1, total: 2 } }); const rows = readFileSync(join(p, "requests.jsonl"), "utf8"); expect(rows).toContain('"patchStatus":"shadow"'); expect(rows).toContain('"cacheWriteTokens":5'); expect(rows).toContain('"catalogDigest":"' + "a".repeat(64)); expect(rows).not.toContain("synthetic secret"); expect(rows).not.toContain("opaque"); });
  it("writes only confirmed provider values in enforce mode and resets session hashes", async () => { const p = dir(); const h = new ExtensionHarness(); await createExtension({ load: config(p, "enforce"), activation, telemetryNonce: () => Math.random().toString() })(h.api()); h.start(); expect(await run(h)).toMatchObject({ reasoning: { effort: "high" } }); h.message("stop"); h.shutdown(); h.start(); await run(h); h.message("stop"); const rows = readFileSync(join(p, "requests.jsonl"), "utf8").trim().split("\n").map((line) => JSON.parse(line) as { locallyAppliedProviderValue?: string; sessionHash: string }); expect(rows[0]!.locallyAppliedProviderValue).toBe("high"); expect(new Set(rows.map((r) => r.sessionHash)).size).toBe(2); });
  it("keeps routing alive with telemetry disabled", async () => { const h = new ExtensionHarness(); await createExtension({ load: config(dir(), "enforce", false), activation })(h.api()); h.start(); expect(await run(h)).toMatchObject({ reasoning: { effort: "high" } }); });
  it("uses the canonical expanded prompt only after the typed opt-in, bounded to 4096 characters", async () => {
    const p = dir(); const h = new ExtensionHarness(); await createExtension({ load: config(p, "enforce", true, true), activation })(h.api()); h.start();
    const expanded = `expanded-${"x".repeat(5_000)}`; h.input("raw prompt secret"); h.before(expanded); h.request({ reasoning: { effort: "provider-secret" }, tools: ["tool-secret"], files: ["file-secret"] }); h.message("stop");
    const decision = records(p, "decisions.jsonl")[0]!; const all = readFileSync(join(p, "decisions.jsonl"), "utf8") + readFileSync(join(p, "requests.jsonl"), "utf8");
    expect(decision).toMatchObject({ promptText: expanded.slice(0, 4096), promptChars: expanded.length }); expect(all).not.toContain("raw prompt secret"); expect(all).not.toContain("provider-secret"); expect(all).not.toContain("tool-secret"); expect(all).not.toContain("file-secret");
  });
  it("keeps prompt text absent by default and when explicitly false", async () => {
    expect(safeDefaults.telemetry.includePromptText).toBe(false);
    for (const includePromptText of [safeDefaults.telemetry.includePromptText, false]) { const p = dir(); const h = new ExtensionHarness(); await createExtension({ load: config(p, "shadow", true, includePromptText), activation })(h.api()); h.start(); await run(h, "do not persist"); h.message("stop"); const decision = records(p, "decisions.jsonl")[0]!; expect(decision.promptText).toBeUndefined(); expect(decision.promptChars).toBe(0); expect(JSON.stringify(decision)).not.toContain("do not persist"); }
  });
  it("uses the session cwd for a relative directory and tolerates deletion and writer recovery", async () => {
    const root = dir(); const relative = "relative/telemetry"; const h = new ExtensionHarness(); h.cwd = root; await createExtension({ load: config(relative, "enforce"), activation })(h.api()); h.start(); await run(h); rmSync(join(root, relative), { recursive: true, force: true }); h.message("stop"); expect(existsSync(join(root, relative, "requests.jsonl"))).toBe(true);
    const blocked = join(root, "blocked"); writeFileSync(blocked, "not-a-directory"); const bad = new ExtensionHarness(); await createExtension({ load: config(blocked, "enforce"), activation })(bad.api()); bad.start(); expect(await run(bad)).toMatchObject({ reasoning: { effort: "high" } }); bad.message("stop"); rmSync(blocked, { force: true }); expect(await run(bad)).toMatchObject({ reasoning: { effort: "high" } }); bad.message("stop"); expect(existsSync(join(blocked, "requests.jsonl"))).toBe(true);
  });
  it("marks repeated provider calls without a new decision and does not attach decision provenance", async () => {
    const p = dir(); const h = new ExtensionHarness(); await createExtension({ load: config(p, "enforce"), activation })(h.api()); h.start(); await run(h); h.message("stop"); expect(h.request({ reasoning: {} })).toMatchObject({ reasoning: { effort: "high" } }); h.message("stop");
    const rows = records(p, "requests.jsonl"); const repeated = rows[1]!; expect(repeated).toMatchObject({ correlationError: "no_decision", patchStatus: "applied" }); expect(repeated.decisionId).toBeUndefined(); expect((repeated.profile as Record<string, unknown>).selector).toBeUndefined(); expect((repeated.profile as Record<string, unknown>).requested).toBeUndefined();
  });
  it("terminates pending telemetry at session boundaries before a clean new request can correlate", async () => {
    const p = dir(); const h = new ExtensionHarness(); await createExtension({ load: config(p, "enforce", true), activation, telemetryNonce: () => Math.random().toString() })(h.api()); h.start(); await run(h); h.shutdown(); h.start(); await run(h); h.message("stop");
    const rows = records(p, "requests.jsonl"); expect(rows[0]).toMatchObject({ correlationError: "session_boundary" }); expect(rows[1]).not.toHaveProperty("correlationError"); expect(rows[0]!.sessionHash).not.toBe(rows[1]!.sessionHash);
  });
  it("flushes a pending request on model reconciliation and settlement before a later clean response", async () => {
    const p = dir(); const h = new ExtensionHarness(); await createExtension({ load: config(p, "enforce"), activation })(h.api()); h.start(); await run(h); h.setModel({ provider: "other" }); expect(h.request({ reasoning: {} })).toBeUndefined(); h.setModel({ provider: "openai" }); await run(h); h.message("stop"); await run(h); h.settled();
    const rows = records(p, "requests.jsonl"); expect(rows[0]).toMatchObject({ correlationError: "profile_boundary" }); expect(rows[1]).not.toHaveProperty("correlationError"); expect(rows[2]).toMatchObject({ correlationError: "settled_boundary" });
  });
  it("retains present zero usage and complete cost while omitting absent or malformed fields", async () => {
    const p = dir(); const h = new ExtensionHarness(); await createExtension({ load: config(p), activation })(h.api()); h.start(); await run(h); h.message("stop", { input: 0, output: 0, reasoning: 0, cacheRead: 0, cacheWrite: 0, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } }); await run(h); h.message("stop", { input: Number.NaN, output: 2, cost: { input: 1, output: "bad", cacheRead: 1, cacheWrite: 1, total: 3 } }); await run(h); h.message("stop");
    const [zero, malformed, absent] = records(p, "requests.jsonl"); expect(zero).toMatchObject({ inputTokens: 0, outputTokens: 0, reasoningTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, cost: { total: 0 } }); expect(malformed).toMatchObject({ outputTokens: 2 }); expect(malformed).not.toHaveProperty("inputTokens"); expect(malformed).not.toHaveProperty("cost"); expect(absent).not.toHaveProperty("inputTokens");
  });
});
